" Plugins (via plugged)
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-sensible'
Plug 'altercation/vim-colors-solarized'
Plug 'tpope/vim-fugitive'
Plug 'scrooloose/nerdtree'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'vim-syntastic/syntastic'
" Plug 'Valloric/YouCompleteMe'
Plug 'PProvost/vim-markdown-jekyll'
call plug#end()

" Basic Settings
filetype on
syntax on
set background=dark
" let g:solarized_termcolors=256
colorscheme solarized
set wildignore=*.pyc
set visualbell
set noerrorbells
set colorcolumn=80
set number
set hlsearch
set incsearch

" Launch nerdtree with the command `vim`
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif

" Status bar
set laststatus=2
set statusline=%f
set statusline+=%=
set statusline+=%{fugitive#statusline()}
set statusline+=\ -
set statusline+=\ %l/%L

" Crutches for me to get used to vim:
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>

" Commands
let mapleader=" "
map <leader>s :source ~/.vim/vimrc<CR>
map <leader>n :NERDTreeToggle<CR>
map <leader>gs :Gstatus<CR>

" Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" Language specific

" Jekyll / Markdown / Mathjax
" TODO Figure out how to offload this into a separate file
autocmd BufRead,BufNewFile,BufEnter *.md,*.markdown set filetype=markdown

function! MathAndLiquid()
    "" Define certain regions
    " Block math. Look for "$$[anything]$$"
    syn region math start=/\$\$/ end=/\$\$/
    " inline math. Look for "$[not $][anything]$"
    syn match math_block '\$[^$].\{-}\$'

    " Liquid single line. Look for "{%[anything]%}"
    syn match liquid '{%.*%}'
    " Liquid multiline. Look for "{%[anything]%}[anything]{%[anything]%}"
    syn region highlight_block start='{% highlight .*%}' end='{%.*%}'
    " Fenced code blocks, used in GitHub Flavored Markdown (GFM)
    syn region highlight_block start='```' end='```'

    "" Actually highlight those regions.
    hi link math Statement
    hi link liquid Statement
    hi link highlight_block Function
    hi link math_block Function
endfunction

autocmd BufRead,BufNewFile,BufEnter *.md,*.markdown call MathAndLiquid()
