" Plugins (via plugged)
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-sensible'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-unimpaired'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-ragtag'
Plug 'tpope/vim-commentary'
Plug 'altercation/vim-colors-solarized'
Plug 'scrooloose/nerdtree'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'ervandew/supertab'
Plug 'jiangmiao/auto-pairs'
Plug 'davidhalter/jedi-vim'
Plug 'Vimjas/vim-python-pep8-indent'
Plug 'PProvost/vim-markdown-jekyll'
Plug 'lervag/vimtex'
Plug 'w0rp/ale'
Plug 'isruslan/vim-es6'
Plug 'mxw/vim-jsx'
Plug 'prettier/vim-prettier', {
\ 'do': 'yarn install',
\ 'for': ['javascript', 'typescript', 'css', 'less', 'scss', 'json', 'graphql', 'vue'] 
\}
call plug#end()

" Basic Settings
filetype plugin indent on
syntax on
set noswapfile
set background=dark
" let g:solarized_termcolors=256
colorscheme solarized
set wildignore=*.pyc
set visualbell
set noerrorbells
set colorcolumn=80
set number
set hlsearch
set clipboard^=unnamed " copy to the system clipboard

" Mouse
set mouse=a
map <LeftMouse> <nop>
map <2-LeftMouse> <nop>

" Indentation
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

" Disable arrow keys 
map <up> <nop>
map <down> <nop>
map <left> <nop>
map <right> <nop>

" Status bar
set laststatus=2
set statusline=%f
set statusline+=%=
set statusline+=%{fugitive#statusline()}
set statusline+=\ -
set statusline+=\ %l/%L

" Mappings
let mapleader=" "
map <leader>s :source ~/.vim/vimrc<CR>:nohls<CR>
map <leader>gs :Gstatus<CR>
map <leader>h :nohls<CR>
noremap <C-l> :tabn<CR>
noremap <C-h> :tabp<CR>
set pastetoggle=<leader>p

" Nerdtree Settings
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
map <C-n> :NERDTreeToggle<CR>

let g:ale_pattern_options = {'.*\.tex$': {'ale_enabled': 0}}

" Supertab Settings
let g:SuperTabDefaultCompletionType = "context"

" Jedi-Vim Settings
let g:jedi#popup_on_dot = 0

" Language specific

" JS
let g:prettier#autoformat = 0
let g:prettier#quickfix_auto_focus = 0
let g:prettier#config#tab_width = 4
let g:prettier#config#print_width = 140
let g:prettier#config#bracket_spacing = 'true'
let g:prettier#config#trailing_comma = 'es5'
let g:prettier#config#jsx_bracket_same_line = 'false'
set suffixesadd+=.js
let g:jsx_ext_required = 0 " Allow JSX in normal JS files
autocmd BufWritePre *.js,*.jsx,*.mjs,*.ts,*.tsx,*.css,*.less,*.scss,*.json,*.graphql,*.vue PrettierAsync

" Jekyll / Markdown / Mathjax
" TODO Figure out how to offload this into a separate file
autocmd BufRead,BufNewFile,BufEnter *.md,*.markdown set filetype=markdown

function! MathAndLiquid()
    "" Define certain regions
    " Block math. Look for "$$[anything]$$"
    syn region math start=/\$\$/ end=/\$\$/
    " inline math. Look for "$[not $][anything]$"
    syn match math_block '\$[^$].\{-}\$'

    " Liquid single line. Look for "{%[anything]%}"
    syn match liquid '{%.*%}'
    " Liquid multiline. Look for "{%[anything]%}[anything]{%[anything]%}"
    syn region highlight_block start='{% highlight .*%}' end='{%.*%}'
    " Fenced code blocks, used in GitHub Flavored Markdown (GFM)
    syn region highlight_block start='```' end='```'

    "" Actually highlight those regions.
    hi link math Statement
    hi link liquid Statement
    hi link highlight_block Function
    hi link math_block Function
endfunction

autocmd BufRead,BufNewFile,BufEnter *.md,*.markdown call MathAndLiquid()
