# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# CLI tools installed via brew:
#   fzf        - fuzzy finder
#   fd         - fast file finder (find replacement)
#   pyenv      - Python version management
#   uv         - Python package/project management
#   powerlevel10k - zsh prompt theme

#----------Standard Oh my ZSH settings----------#

# If you come from bash you might have to change your $PATH.

# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME"/.oh-my-zsh

# Set name of the theme to load. Optionally, if you set this to "random"
# it'll load a random theme each time that oh-my-zsh is loaded.
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
source $(brew --prefix powerlevel10k)/share/powerlevel10k/powerlevel10k.zsh-theme
ZSH_THEME=""

#The agnoster theme suppresses the username for the default user.
DEFAULT_USER="paul"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.

export VISUAL=vim
export EDITOR="$VISUAL"

plugins=(web-search fzf)

source $ZSH/oh-my-zsh.sh

#----------Aliases and scripts----------#
#
export PATH="/Users/paul/.local/bin:$PATH"
export PATH="/opt/homebrew/bin:$PATH" # Adds homebrew-install stuff to the PATH - specific to Apple silicon
alias groot='cd $(git root)' # Assumes root has been aliased to `rev-parse --show-toplevel` in gitconfig

#----------Prompt customization----------#

PS1="$PS1"$'\n'" ➜  "
export VIRTUAL_ENV_DISABLE_PROMPT=1

#----------Shell configuration----------#

# eval "$(/opt/homebrew/bin/brew shellenv)" # Set PATH, MANPATH, etc., for Homebrew.
export KEYTIMEOUT=1 # Fixes problem with vi-mode reverse search
bindkey -v  # Vi mode for the shell
ZLE_REMOVE_SUFFIX_CHARS=$' \t\n;&' # Fixes behavior involving autocomplete and pipes
test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
# bindkey "≥" insert-last-word # This allows alt-. to insert the last word of the last command (i.e. !$)

#----------fzf----------#

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
_fd_exclude="--exclude .git --exclude node_modules --exclude .venv --exclude __pycache__ --exclude .cache --exclude .npm --exclude .nvm --exclude .pyenv --exclude .vim --exclude .vscode --exclude .claude --exclude Library --exclude .Trash --exclude Applications --exclude Movies --exclude Music --exclude Pictures"
z() { local dir=$(fd --type d --hidden ${=_fd_exclude} . ~ 2>/dev/null | fzf --query="$1"); [ -n "$dir" ] && cd "$dir"; }
v() { local file=$(fd --type f --hidden ${=_fd_exclude} . ~ 2>/dev/null | fzf --query="$1"); [ -n "$file" ] && vim "$file"; }

#----------Python----------#

export PIP_REQUIRE_VIRTUALENV=true
export JUPYTERLAB_DIR="$HOME/.local/share/jupyter_labextensions"

#----------NVM----------#

export NVM_DIR="$HOME/.nvm"
alias loadnvm="[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh""  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

#----------Defaults----------#

export BROWSER=/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
