export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# The next line updates PATH for the Google Cloud SDK.
if [ -f /Users/paul/google-cloud-sdk/path.bash.inc ]; then
  source '/Users/paul/google-cloud-sdk/path.bash.inc'
fi

# The next line enables shell command completion for gcloud.
if [ -f /Users/paul/google-cloud-sdk/completion.bash.inc ]; then
  source '/Users/paul/google-cloud-sdk/completion.bash.inc'
fi

alias bw="cd /Users/paul/bw"
alias kgs="java -jar /Users/paul/cgoban.jar"

c++11() {
	g++ -Wall -std=c++11 "$1"
}

export BROWSER=/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome
export VISUAL=vim
export EDITOR="$VISUAL"
