export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

bwnetwork=/Users/paul/bw/bwnetwork
bw=/Users/paul/bw
# The next line updates PATH for the Google Cloud SDK.
if [ -f /Users/paul/google-cloud-sdk/path.bash.inc ]; then
  source '/Users/paul/google-cloud-sdk/path.bash.inc'
fi

# The next line enables shell command completion for gcloud.
if [ -f /Users/paul/google-cloud-sdk/completion.bash.inc ]; then
  source '/Users/paul/google-cloud-sdk/completion.bash.inc'
fi

alias bash_profile="atom /Users/paul/.bash_profile"
alias bw="cd /Users/paul/bw"
alias kgs="java -jar /Users/paul/cgoban.jar"
alias desktop="cd /Users/paul/Desktop"
alias downloads="cd /Users/paul/Downloads"

c++11() {
	g++ -Wall -std=c++11 "$1"
}
export PATH="/usr/local/opt/openssl/bin:$PATH"
